version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: avik32223/gala-event-api
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t $IMAGE_NAME:latest
  workflows:
    version: 2
    build-master:
      jobs:
        - build:
          filters:
            branches:
              only: master
